name: Deploy and Run on GitHub Pages

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy_html_js_css:
    environment:
      name: github-pages
      url: ${{ steps.deployment_html_js_css.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Adjust the Node.js version as needed
      - name: Live Preview Action
  # You may pin to the exact commit or the version.
  # uses: sharadcodes/live-preview-action@c54cd3cb3eb706435dc16661ea35356261835d5d
        uses: sharadcodes/live-preview-action@v1.0
        with:
        port: 3000
        minutes: 10  # optional, adjust as needed
        command: npm install && npm start
       
  
          

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Adjust if your project uses a different build command

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload the entire repository

      - name: Deploy to GitHub Pages
        id: deployment_html_js_css
        uses: actions/deploy-pages@v2
